<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == "encik":
        return 'fuck u understand'
    else:
        return f'good morning {name}!'

greeting("encik")

'fuck u understand'

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [4]:
function = lambda name: f'fuck u {name}'

function(name = "udhaya")

'fuck u udhaya'

### 1.4 Optional arguments

In [8]:
def greeting(name = 'bruh'):
    if name == 'encik':
        return "fuck u understand"
    else:
        return f"dumbass {name}"

greeting(name = 'encik')

'fuck u understand'

## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [9]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting(name = 'sum fuk')

'Hello sum fuk!'

The function is given a default return case for the condition that name does not = Batman

## Exercise 2 :  Calculator functions

In [17]:
def add(x,y):
    return x+y

import numpy as np

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)

array([100, 100, 100, 100, 100])

In [18]:
def subtract(x,y):
    return x-y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

subtract(x,y)

array([-28, -32, -12,  52, -46])

In [19]:
def multiply(x,y):
    return x*y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [30]:
def divide(x,y):
    if (y == 0).any():
        return "you done fucked up"
    else:
        return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
z = np.array([0,1,2,3,4])
    
divide(x,z)

'you done fucked up'

## Exercise 3 :  max_info() with NumPy

In [9]:
test_array = np.array([69,12,34,65,78])
np.argmax(test_array)

4

In [10]:
import numpy as np

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)

max_info(numbers)

(83, 2)