<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [2]:
import numpy as np

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [3]:
py_mods = ["CM1102", "HSH1000", "HSA1000"]
py_grades = ["ez A+", "S/U", "S/U as well"]

print(py_mods[1])
print(py_grades[1])

HSH1000
S/U


### 1.3 Accessing data from a dictionary

In [4]:
module_grades = {"CM1102":"ez A+",
                "HSH1000":"S/U man",
                "DTK1234":"Just S/U"
                }

print(module_grades["CM1102"])

ez A+


### 1.4 Higher dimensional lists

In [8]:
py_module_grades = [["CM1102","ez A+"],
                   ["HSH1000", "S/U"],
                   ["HSA1000", "Also S/U"]]

## 2 Lists vs. Arrays

### 2.1 Size

In [9]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

len(py_list_2d)
len(np_array_2d)

10

### 2.2 Arrays are fussy about type

In [10]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [16]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      

sum(py_list)

15

## Exercise 1 :  Total recall?

1. Both lists and arrays are able to store values, and mathematical functions can be applied on them
2. Multiplying a list by a number expands it, while multiplying an array by a number multiplies every element in it
Adding 2 lists together combines all elements into 1 list, while adding 2 arrays sums up each corresponding element
3. A dictionary is a form of data storage that pairs values with a set of keys

## Exercise 2 :  Index me

In [25]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[0], py_list[2], py_list[4], py_list[6], py_list[8])   # Prints 'i9'

a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [26]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [39]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_array = np.array(numbers)

array = np_array == 1

array.sum()

9